server:
  port: 8084

hm:
  db:
    database: hm-trade
  mq:
    seckill:
      enabled: true
  swagger:
    title: "ZMall交易服务接口文档"
    package: com.hmall.trade.controller
spring:
  data:
    redis:
      database: 1
  rabbitmq:
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
