server:
  port: 8083

hm:
  db:
    database: hm-user
  swagger:
    title: "ZMall用户服务接口文档"
    package: com.hmall.user.controller
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
