server:
  port: 8085

hm:
  db:
    database: hm-pay
  swagger:
    title: "ZMall支付服务接口文档"
    package: com.hmall.pay.controller
spring:
  rabbitmq:
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
