server:
  port: 8081

hm:
  db:
    database: hm-item
  swagger:
    title: "ZMall商品服务接口文档"
    package: com.hmall.item.controller
  # OSS配置（如果以下信息都填写了则使用OSS，留空则使用本地存储）
  oss:
    endpoint:
    access-key-id:
    access-key-secret:
    bucket-name:
  # 本地文件上传配置
  upload:
    base-path: ../zmall-nginx/html/uploads
    url-prefix: /uploads/

spring:
  data:
    redis:
      database: 2
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
